---
title: "MLB Elo Ratings"
format:
  html:
    embed-resources: true
    fig-align: center
    df-print: paged
echo: false
---

```{r}
#| message: false
# load required packages
library(httr)
library(jsonlite)
library(tidyverse)
library(dplyr)
library(stringr)
library(tibble)
library(tidyr)
library(purrr)
library(mlbplotR)
library(gt)
```

```{r}
#| message: false
# load data
elo_ratings = readRDS("elo_rating.rds")
```

```{r}
latest_elo_df <- elo_ratings %>%
  group_by(Team) %>%
  filter(Date == max(Date)) %>%
  ungroup()

latest_elo_df %>%
  select(Rank, "Logo" = team_logo_espn, Team, `Elo Rating`, 
         `Daily Elo Change`, Wins, Losses) %>%
  gt() %>%
  text_transform(
    locations = cells_body(c(Logo)),
    fn = function(x) {
      web_image(url = x, height = 40)
    }
  )

```

```{r}
#| fig-width: 15
#| fig-height: 17
#| message: false

# Compute min and max Elo rounded to nearest 5
min_elo <- floor(min(elo_ratings$`Elo Rating`, na.rm = TRUE) / 5) * 5
true_max_elo <- max(elo_ratings$`Elo Rating`, na.rm = TRUE)
max_elo <- ceiling(true_max_elo / 5) * 5

# Ensure top break is strictly greater than true max Elo
max_break <- max_elo + ifelse(max_elo == true_max_elo, 5, 0)

# Breaks every 25 Elo points across the range
base_breaks <- seq(min_elo, max_break, by = 20)

# Add 1500, min_elo, and max_break manually
custom_breaks <- sort(unique(c(base_breaks, 1500, min_elo, max_break)))

ggplot(elo_ratings, aes(x = as.Date(Date), y = `Elo Rating`, group = team_abbr, color = team_abbr)) +
  geom_line(linewidth = 1) +
  geom_mlb_scoreboard_logos(
    data = latest_elo_df,
    mapping = aes(x = as.Date(Date), y = `Elo Rating`, team_abbr = team_abbr),
    inherit.aes = FALSE,
    width = 0.04
  ) +
  scale_color_mlb(type = "primary") +
  scale_y_continuous(
  limits = c(min_elo, max_break),
  breaks = custom_breaks
  ) + 
  scale_x_date(
    limits = c(min(as.Date(elo_ratings$Date)), max(as.Date(elo_ratings$Date)) + 1),
    breaks = seq(min(as.Date(elo_ratings$Date)), max(as.Date(elo_ratings$Date)), length.out = 6),
    date_labels = "%b %d"
  ) +
  labs(
    title = "MLB Elo Ratings Over Time",
    x = "Date",
    y = "Elo Rating"
  ) +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.text = element_text(size = 18),
    axis.title = element_text(size = 20),
    plot.title = element_text(size = 28),
    legend.text = element_text(size = 16)
  )

```

Last Updated: `r {Sys.setenv(TZ = "America/Chicago"); format(Sys.time(), "%Y-%m-%d %H:%M %Z")}`
