name: daily-render-and-publish

on:
  schedule:
    - cron: '0 10 * * *'   # 5:00 AM CDT
    - cron: '0 3 * * *'    # 10:00 PM CDT (22)
    - cron: '0 5 * * *'    # 12:00 AM CDT
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
        - name: Checkout repo
          uses: actions/checkout@v3
          
        - name: Try r2u setup (fast method)
          id: r2u
          continue-on-error: true
          uses: eddelbuettel/github-actions/r2u-setup@master
  
        - name: Fallback R setup (if r2u fails)
          if: steps.r2u.outcome == 'failure'
          uses: r-lib/actions/setup-r@v2
  
        - name: Set up Quarto
          uses: quarto-dev/quarto-actions/setup@v2
          
        - name: Cache R packages
          uses: actions/cache@v3
          with:
            path: ~/.local/share/R
            key: ${{ runner.os }}-r-pkg-${{ hashFiles('**/DESCRIPTION') }}
            restore-keys: |
              ${{ runner.os }}-r-pkg-

        # - name: Setup r2u
        #   uses: eddelbuettel/github-actions/r2u-setup@master
        # 
        # - name: Set up Quarto
        #   uses: quarto-dev/quarto-actions/setup@v2
        # 
        - name: Install CRAN packages
          run: Rscript -e 'install.packages(c("gt", "httr", "jsonlite", "tidyverse", "mlbplotR"))'
          
        - name: Run get_datatable.R
          run: Rscript get_datatable.R

        - name: Render with Quarto
          run: quarto render

        - name: Publish to GitHub Pages
          uses: quarto-dev/quarto-actions/publish@v2
          with:
            render: false
            target: gh-pages

